### ISSUE TITLE
Please note the version id.

### ISSUE THREAD

**Issue by SzotsGabor** [crippa1337/svart#23]
Version 2 still displays 1.0.0.

Gabor Szots, CCRL

**Comment by crippa1337** [comment]
> Version 2 still displays 1.0.0.
> 
> Gabor Szots, CCRL

Thank you. I will update the binaries.

**Comment by crippa1337** [comment]
@SzotsGabor I have updated the binaries in the Svart 2 release. Let me know if the issue has been resolved.

**Comment by SzotsGabor** [comment]
Yes, it is now 2.0.0.

BTW, do you prefer to remain anonym? We like to include author name and country in our lists. It is completely your decision, it is not a requirement for your engine to be tested.

I see you are from Sweden. I guess Svart means sword, right? Just out of curiosity, I am fond of languages.

**Comment by crippa1337** [comment]
> Yes, it is now 2.0.0.
> 
> BTW, do you prefer to remain anonym? We like to include author name and country in our lists. It is completely your decision, it is not a requirement for your engine to be tested.
> 
> I see you are from Sweden. I guess Svart means sword, right? Just out of curiosity, I am fond of languages.

Good guess! It means ``black`` in Swedish, ``svärd`` would be sword.
Regarding the name, I am fine with my first name being used, my name is Cristopher; but I would prefer to not reveal my last name. My name could be displayed as ``Crippa / Cristopher`` or just one of them, that is up to you. 🙂
