### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by SzotsGabor** [crippa1337/svart#43]
Hi,

I wonder if 4 or 4.0.0 is your preferred version number. I like to keep it simple, so Svart 4, but on our list there is Svart 2.0.0 and Svart 3 which does not look very nice to the eyes.

**Comment by crippa1337** [comment]
Hey again Gabor!

I also prefer the short version, hence why the UCI output should be ``Svart 4``.
I previously was unsure with my v2 release and that's why it's 2.0.0. You're free to change it to just 2, I would even prefer that as well.
